/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 26-Feb-2023 4:04:38 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Views */

DROP VIEW IF EXISTS `VIEW_A` CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS `Grade` CASCADE
;

DROP TABLE IF EXISTS `Group` CASCADE
;

DROP TABLE IF EXISTS `GroupMembers` CASCADE
;

DROP TABLE IF EXISTS `Message` CASCADE
;

DROP TABLE IF EXISTS `User` CASCADE
;

/* Create Tables */

CREATE TABLE `Grade`
(
	`Id` INT NOT NULL,
	`TeacherId` INT NOT NULL,
	`StudentId` INT NOT NULL,
	`GroupId` INT NOT NULL,
	`Grade` INT NOT NULL,
	`Description` VARCHAR(100) NULL,
	`CreatedAt` DATE NOT NULL,
	CONSTRAINT `PK_Grade` PRIMARY KEY (`Id` ASC)
)

;

CREATE TABLE `Group`
(
	`Id` INT NOT NULL,
	`Name` VARCHAR(50) NULL,
	`Code` VARCHAR(7) NULL,
	CONSTRAINT `PK_Groups` PRIMARY KEY (`Id` ASC)
)

;

CREATE TABLE `GroupMembers`
(
	`Id` INT NOT NULL,
	`UserId` INT NOT NULL,
	`GroupId` INT NOT NULL,
	CONSTRAINT `PK_GroupMembers` PRIMARY KEY (`Id` ASC)
)

;

CREATE TABLE `Message`
(
	`Id` INT NOT NULL,
	`From` INT NOT NULL,
	`ToUser` INT NULL,
	`ToGroup` INT NULL,
	`Title` VARCHAR(50) NULL,
	`Text` VARCHAR(2000) NOT NULL,
	`CreatedAt` DATE NOT NULL,
	CONSTRAINT `PK_Message` PRIMARY KEY (`Id` ASC)
)

;

CREATE TABLE `User`
(
	`Id` INT NOT NULL,
	`FirstName` VARCHAR(50) NOT NULL,
	`Lastname` VARCHAR(50) NOT NULL,
	`Email` VARCHAR(50) NOT NULL,
	`PasswordHash` VARCHAR(128) NOT NULL,
	`Address` VARCHAR(50) NULL,
	`PhoneNumber` VARCHAR(15) NULL,
	`IsTeacher` BOOL NULL DEFAULT False,
	CONSTRAINT `PK_User` PRIMARY KEY (`Id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Grade` 
 ADD INDEX `IXFK_Grade_GroupMembers` (`GroupId` ASC)
;

ALTER TABLE `Grade` 
 ADD INDEX `IXFK_Grade_User` (`TeacherId` ASC)
;

ALTER TABLE `Grade` 
 ADD INDEX `IXFK_Grade_User_02` (`StudentId` ASC)
;

ALTER TABLE `GroupMembers` 
 ADD INDEX `IXFK_GroupMembers_Groups` (`GroupId` ASC)
;

ALTER TABLE `GroupMembers` 
 ADD INDEX `IXFK_GroupMembers_User` (`UserId` ASC)
;

ALTER TABLE `Message` 
 ADD INDEX `IXFK_Message_GroupMembers` (`ToGroup` ASC)
;

ALTER TABLE `Message` 
 ADD INDEX `IXFK_Message_User` (`From` ASC)
;

ALTER TABLE `Message` 
 ADD INDEX `IXFK_Message_User_02` (`ToUser` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Grade` 
 ADD CONSTRAINT `FK_Grade_GroupMembers`
	FOREIGN KEY (`GroupId`) REFERENCES `GroupMembers` (`Id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Grade` 
 ADD CONSTRAINT `FK_Grade_User`
	FOREIGN KEY (`TeacherId`) REFERENCES `User` (`Id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Grade` 
 ADD CONSTRAINT `FK_Grade_User_02`
	FOREIGN KEY (`StudentId`) REFERENCES `User` (`Id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `GroupMembers` 
 ADD CONSTRAINT `FK_GroupMembers_Groups`
	FOREIGN KEY (`GroupId`) REFERENCES `Group` (`Id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `GroupMembers` 
 ADD CONSTRAINT `FK_GroupMembers_User`
	FOREIGN KEY (`UserId`) REFERENCES `User` (`Id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Message` 
 ADD CONSTRAINT `FK_Message_GroupMembers`
	FOREIGN KEY (`ToGroup`) REFERENCES `GroupMembers` (`Id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Message` 
 ADD CONSTRAINT `FK_Message_User`
	FOREIGN KEY (`From`) REFERENCES `User` (`Id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Message` 
 ADD CONSTRAINT `FK_Message_User_02`
	FOREIGN KEY (`ToUser`) REFERENCES `User` (`Id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
/* Create Views */

CREATE OR REPLACE VIEW `VIEW_A` AS 
/* SQL statements defining VIEW_A */
;

